/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfessorRouteImport } from './routes/_authenticated.professor'
import { Route as AuthenticatedAlunoRouteImport } from './routes/_authenticated.aluno'
import { Route as AuthenticatedProfessorIndexRouteImport } from './routes/_authenticated.professor.index'
import { Route as AuthenticatedProfessorMensalidadesRouteImport } from './routes/_authenticated.professor.mensalidades'
import { Route as AuthenticatedProfessorGraduacoesRouteImport } from './routes/_authenticated.professor.graduacoes'
import { Route as AuthenticatedProfessorFotosRouteImport } from './routes/_authenticated.professor.fotos'
import { Route as AuthenticatedProfessorCampeonatosRouteImport } from './routes/_authenticated.professor.campeonatos'
import { Route as AuthenticatedProfessorCalendarioRouteImport } from './routes/_authenticated.professor.calendario'
import { Route as AuthenticatedProfessorAlunosRouteImport } from './routes/_authenticated.professor.alunos'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfessorRoute = AuthenticatedProfessorRouteImport.update({
  id: '/professor',
  path: '/professor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlunoRoute = AuthenticatedAlunoRouteImport.update({
  id: '/aluno',
  path: '/aluno',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfessorIndexRoute =
  AuthenticatedProfessorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProfessorRoute,
  } as any)
const AuthenticatedProfessorMensalidadesRoute =
  AuthenticatedProfessorMensalidadesRouteImport.update({
    id: '/mensalidades',
    path: '/mensalidades',
    getParentRoute: () => AuthenticatedProfessorRoute,
  } as any)
const AuthenticatedProfessorGraduacoesRoute =
  AuthenticatedProfessorGraduacoesRouteImport.update({
    id: '/graduacoes',
    path: '/graduacoes',
    getParentRoute: () => AuthenticatedProfessorRoute,
  } as any)
const AuthenticatedProfessorFotosRoute =
  AuthenticatedProfessorFotosRouteImport.update({
    id: '/fotos',
    path: '/fotos',
    getParentRoute: () => AuthenticatedProfessorRoute,
  } as any)
const AuthenticatedProfessorCampeonatosRoute =
  AuthenticatedProfessorCampeonatosRouteImport.update({
    id: '/campeonatos',
    path: '/campeonatos',
    getParentRoute: () => AuthenticatedProfessorRoute,
  } as any)
const AuthenticatedProfessorCalendarioRoute =
  AuthenticatedProfessorCalendarioRouteImport.update({
    id: '/calendario',
    path: '/calendario',
    getParentRoute: () => AuthenticatedProfessorRoute,
  } as any)
const AuthenticatedProfessorAlunosRoute =
  AuthenticatedProfessorAlunosRouteImport.update({
    id: '/alunos',
    path: '/alunos',
    getParentRoute: () => AuthenticatedProfessorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/aluno': typeof AuthenticatedAlunoRoute
  '/professor': typeof AuthenticatedProfessorRouteWithChildren
  '/professor/alunos': typeof AuthenticatedProfessorAlunosRoute
  '/professor/calendario': typeof AuthenticatedProfessorCalendarioRoute
  '/professor/campeonatos': typeof AuthenticatedProfessorCampeonatosRoute
  '/professor/fotos': typeof AuthenticatedProfessorFotosRoute
  '/professor/graduacoes': typeof AuthenticatedProfessorGraduacoesRoute
  '/professor/mensalidades': typeof AuthenticatedProfessorMensalidadesRoute
  '/professor/': typeof AuthenticatedProfessorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/aluno': typeof AuthenticatedAlunoRoute
  '/professor/alunos': typeof AuthenticatedProfessorAlunosRoute
  '/professor/calendario': typeof AuthenticatedProfessorCalendarioRoute
  '/professor/campeonatos': typeof AuthenticatedProfessorCampeonatosRoute
  '/professor/fotos': typeof AuthenticatedProfessorFotosRoute
  '/professor/graduacoes': typeof AuthenticatedProfessorGraduacoesRoute
  '/professor/mensalidades': typeof AuthenticatedProfessorMensalidadesRoute
  '/professor': typeof AuthenticatedProfessorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/aluno': typeof AuthenticatedAlunoRoute
  '/_authenticated/professor': typeof AuthenticatedProfessorRouteWithChildren
  '/_authenticated/professor/alunos': typeof AuthenticatedProfessorAlunosRoute
  '/_authenticated/professor/calendario': typeof AuthenticatedProfessorCalendarioRoute
  '/_authenticated/professor/campeonatos': typeof AuthenticatedProfessorCampeonatosRoute
  '/_authenticated/professor/fotos': typeof AuthenticatedProfessorFotosRoute
  '/_authenticated/professor/graduacoes': typeof AuthenticatedProfessorGraduacoesRoute
  '/_authenticated/professor/mensalidades': typeof AuthenticatedProfessorMensalidadesRoute
  '/_authenticated/professor/': typeof AuthenticatedProfessorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/aluno'
    | '/professor'
    | '/professor/alunos'
    | '/professor/calendario'
    | '/professor/campeonatos'
    | '/professor/fotos'
    | '/professor/graduacoes'
    | '/professor/mensalidades'
    | '/professor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/aluno'
    | '/professor/alunos'
    | '/professor/calendario'
    | '/professor/campeonatos'
    | '/professor/fotos'
    | '/professor/graduacoes'
    | '/professor/mensalidades'
    | '/professor'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/aluno'
    | '/_authenticated/professor'
    | '/_authenticated/professor/alunos'
    | '/_authenticated/professor/calendario'
    | '/_authenticated/professor/campeonatos'
    | '/_authenticated/professor/fotos'
    | '/_authenticated/professor/graduacoes'
    | '/_authenticated/professor/mensalidades'
    | '/_authenticated/professor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/professor': {
      id: '/_authenticated/professor'
      path: '/professor'
      fullPath: '/professor'
      preLoaderRoute: typeof AuthenticatedProfessorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/aluno': {
      id: '/_authenticated/aluno'
      path: '/aluno'
      fullPath: '/aluno'
      preLoaderRoute: typeof AuthenticatedAlunoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/professor/': {
      id: '/_authenticated/professor/'
      path: '/'
      fullPath: '/professor/'
      preLoaderRoute: typeof AuthenticatedProfessorIndexRouteImport
      parentRoute: typeof AuthenticatedProfessorRoute
    }
    '/_authenticated/professor/mensalidades': {
      id: '/_authenticated/professor/mensalidades'
      path: '/mensalidades'
      fullPath: '/professor/mensalidades'
      preLoaderRoute: typeof AuthenticatedProfessorMensalidadesRouteImport
      parentRoute: typeof AuthenticatedProfessorRoute
    }
    '/_authenticated/professor/graduacoes': {
      id: '/_authenticated/professor/graduacoes'
      path: '/graduacoes'
      fullPath: '/professor/graduacoes'
      preLoaderRoute: typeof AuthenticatedProfessorGraduacoesRouteImport
      parentRoute: typeof AuthenticatedProfessorRoute
    }
    '/_authenticated/professor/fotos': {
      id: '/_authenticated/professor/fotos'
      path: '/fotos'
      fullPath: '/professor/fotos'
      preLoaderRoute: typeof AuthenticatedProfessorFotosRouteImport
      parentRoute: typeof AuthenticatedProfessorRoute
    }
    '/_authenticated/professor/campeonatos': {
      id: '/_authenticated/professor/campeonatos'
      path: '/campeonatos'
      fullPath: '/professor/campeonatos'
      preLoaderRoute: typeof AuthenticatedProfessorCampeonatosRouteImport
      parentRoute: typeof AuthenticatedProfessorRoute
    }
    '/_authenticated/professor/calendario': {
      id: '/_authenticated/professor/calendario'
      path: '/calendario'
      fullPath: '/professor/calendario'
      preLoaderRoute: typeof AuthenticatedProfessorCalendarioRouteImport
      parentRoute: typeof AuthenticatedProfessorRoute
    }
    '/_authenticated/professor/alunos': {
      id: '/_authenticated/professor/alunos'
      path: '/alunos'
      fullPath: '/professor/alunos'
      preLoaderRoute: typeof AuthenticatedProfessorAlunosRouteImport
      parentRoute: typeof AuthenticatedProfessorRoute
    }
  }
}

interface AuthenticatedProfessorRouteChildren {
  AuthenticatedProfessorAlunosRoute: typeof AuthenticatedProfessorAlunosRoute
  AuthenticatedProfessorCalendarioRoute: typeof AuthenticatedProfessorCalendarioRoute
  AuthenticatedProfessorCampeonatosRoute: typeof AuthenticatedProfessorCampeonatosRoute
  AuthenticatedProfessorFotosRoute: typeof AuthenticatedProfessorFotosRoute
  AuthenticatedProfessorGraduacoesRoute: typeof AuthenticatedProfessorGraduacoesRoute
  AuthenticatedProfessorMensalidadesRoute: typeof AuthenticatedProfessorMensalidadesRoute
  AuthenticatedProfessorIndexRoute: typeof AuthenticatedProfessorIndexRoute
}

const AuthenticatedProfessorRouteChildren: AuthenticatedProfessorRouteChildren =
  {
    AuthenticatedProfessorAlunosRoute: AuthenticatedProfessorAlunosRoute,
    AuthenticatedProfessorCalendarioRoute:
      AuthenticatedProfessorCalendarioRoute,
    AuthenticatedProfessorCampeonatosRoute:
      AuthenticatedProfessorCampeonatosRoute,
    AuthenticatedProfessorFotosRoute: AuthenticatedProfessorFotosRoute,
    AuthenticatedProfessorGraduacoesRoute:
      AuthenticatedProfessorGraduacoesRoute,
    AuthenticatedProfessorMensalidadesRoute:
      AuthenticatedProfessorMensalidadesRoute,
    AuthenticatedProfessorIndexRoute: AuthenticatedProfessorIndexRoute,
  }

const AuthenticatedProfessorRouteWithChildren =
  AuthenticatedProfessorRoute._addFileChildren(
    AuthenticatedProfessorRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAlunoRoute: typeof AuthenticatedAlunoRoute
  AuthenticatedProfessorRoute: typeof AuthenticatedProfessorRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAlunoRoute: AuthenticatedAlunoRoute,
  AuthenticatedProfessorRoute: AuthenticatedProfessorRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
